theme = 'dracula'

[editor]
line-number="relative"
mouse = false
auto-pairs = false
auto-format = true

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = ""

[editor.file-picker]
hidden = false

[keys.normal]
C-j = ":set-language java"
